name: "Tofu Apply"

on:
  push:
    branches:
      - main

jobs:
  tofu:
    name: "Tofu"
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VERSION: 1.5.7
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Set the working directory to the root of the repository
          path: "./"

      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve -var 'vm_password=${{ secrets.VM_PASSWORD }}'
        continue-on-error: true
